---
Name: silvershop-stripe-config
After: silvershop-config
---
SilverStripe\Security\Member:
  extensions:
    - Innoweb\SilvershopStripe\Extensions\MemberExtension

SilverStripe\Omnipay\Model\Payment:
  extensions:
    - Innoweb\SilvershopStripe\Extensions\PaymentExtension

SilverStripe\Core\Injector\Injector:
  SilverShop\Checkout\Component\OnsitePayment:
    class: Innoweb\SilvershopStripe\Checkout\Components\StripeOnsitePayment
  SilverShop\Checkout\OrderProcessor:
    class: Innoweb\SilvershopStripe\Checkout\StripeOrderProcessor

Innoweb\SilvershopStripe\Checkout\Components\StripeOnsitePayment:
  enable_saved_cards: true

SilverStripe\Omnipay\GatewayInfo:
  Stripe:
    is_offsite: false
  Stripe_PaymentIntents:
    is_offsite: false

SilverStripe\Omnipay\Service\PurchaseService:
  extensions:
    - Innoweb\SilvershopStripe\Extensions\PaymentIntentPurchaseService
